# Enable rounded corners
rounded-corners = true;
# corner-radius = 10;
# detect-rounded-corners = false;

# Shadow settings
# shadow = true;
# shadow-radius = 12;
# shadow-offset-x = -12;
# shadow-offset-y = -12;
# shadow-opacity = 0.7;

# Transparency settings
opacity-rule = [
    "10:class_g = 'Ghostty'",
    "70:class_g = 'Polybar'"
];

# Blur settings
blur: {
    method = "dual_kawase";
    strength = 7; # Adjust based on preference
    background = true;
};

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

frame-opacity = 0.5;

# Backend (use experimental for better results)
backend = "glx";
vsync = true;
