#! /bin/bash

sudo cpufreq-set -c 0 -g performance
sudo cpufreq-set -c 1 -g performance
sudo cpufreq-set -c 2 -g performance
sudo cpufreq-set -c 3 -g performance
sudo cpufreq-set -c 4 -g performance
sudo cpufreq-set -c 5 -g performance
sudo cpufreq-set -c 6 -g performance
sudo cpufreq-set -c 7 -g performance
sudo cpufreq-set -c 8 -g performance
sudo cpufreq-set -c 9 -g performance
sudo cpufreq-set -c 10 -g performance
sudo cpufreq-set -c 11 -g performance
