#! /bin/bash

sudo cpufreq-set -c 0 -g powersave
sudo cpufreq-set -c 1 -g powersave
sudo cpufreq-set -c 2 -g powersave
sudo cpufreq-set -c 3 -g powersave
sudo cpufreq-set -c 4 -g powersave
sudo cpufreq-set -c 5 -g powersave
sudo cpufreq-set -c 6 -g powersave
sudo cpufreq-set -c 7 -g powersave
sudo cpufreq-set -c 8 -g powersave
sudo cpufreq-set -c 9 -g powersave
sudo cpufreq-set -c 10 -g powersave
sudo cpufreq-set -c 11 -g powersave
