[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#11121d"
foreground = "#a9b1d6"

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "BoldItalic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "MediumItalic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
opacity = 0.5

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 5

[terminal]

[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
blink_interval = 500

[env]
WINIT_X11_SCALE_FACTOR="1.0"
